style(action) : refine output and exception handling

diff --git a/.github/actions/decrypt-pwd/action.yaml b/.github/actions/decrypt-pwd/action.yaml
--- a/.github/actions/decrypt-pwd/action.yaml
+++ b/.github/actions/decrypt-pwd/action.yaml
@@ -24,6 +24,13 @@ runs:
       echo -e "${YELLOW}[ EXECUTING ] > Decrypting password${BLANK}"
       SECRET="${{ inputs.hash-secret }}"
       DECRYPTED_TOKEN=$(gpg --decrypt --quiet --batch --passphrase "$SECRET" --output - <(echo "${{ inputs.token }}" | base64 -d))
+      if [[ $? = 0 ]]
+      then
+        echo -e "${GREEN}[ SUCCESS ] > Decryption success ! ${BLANK}"
+      else
+        echo -e "${RED}[ FAIL ] > Decryption failed ! ${BLANK}"
+        exit 1
+      fi
       echo "::add-mask::$DECRYPTED_TOKEN"
       echo "DECRYPTED_TOKEN=$DECRYPTED_TOKEN" >> $GITHUB_OUTPUT
     shell: bash
diff --git a/.github/actions/encrypt-pwd/action.yaml b/.github/actions/encrypt-pwd/action.yaml
--- a/.github/actions/encrypt-pwd/action.yaml
+++ b/.github/actions/encrypt-pwd/action.yaml
@@ -27,6 +27,13 @@ runs:
       echo "KEY = $KEY"
 
       ENCRYPTED_TOKEN=$(gpg --symmetric --batch --passphrase "$SECRET" --output - <(echo "$KEY") | base64 -w0)
+      if [[ $? = 0 ]]
+      then
+        echo -e "${GREEN}[ SUCCESS ] > Encryption success ! ${BLANK}"
+      else
+        echo -e "${RED}[ FAIL ] > Encryption failed ! ${BLANK}"
+        exit 1
+      fi
       echo "ENCRYPTED_TOKEN=$ENCRYPTED_TOKEN" >> $GITHUB_OUTPUT
     shell: bash
     env:
